version: "3.9"  # optional since v1.27.0
services:
  web:

    build: app/.
    ports:
      - "5000:5000"
    dns:
      - 8.8.8.8
    links:
      - lru
    environment:
      - APP_ID
      - APP_KEY
      - SECRET_KEY
 
    depends_on:
      - lru
    network_mode: "bridge"

  lru:
    build: redis/.
    ports:
      - "6379:6379"
    network_mode: "bridge"


   
