apiVersion: v1
data:
  app_id: ZWNiODk0ZjcK
  app_key: ZmVmYTQ4MWQ0NTMzYzJjMmM5YTM3YzRlOTM2ZjdkMjIK
  secret_key: M2Y1ZjgxYTAyZDdkNTBjZjYyMjQ0OWY1N2MyNTgwMzc3NWQ1OTljZGY3N2JkNjZkZWU0NTQ3ZDdjNDYxZDVlMw==
kind: Secret
metadata:
  name: app-keys
type: Opaque
