---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: app-test
spec:
  ports:
    -
      name: "5000"
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: app
  type: NodePort
