--- 
apiVersion: v1
data: 
  redis.conf: |
      
      maxmemory 1MB
      maxmemory-policy allkeys-lfu
kind: ConfigMap
metadata: 
  labels: 
    app: redis
  name: redis-config
  namespace: app-test