---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lru
  namespace: app-test
spec:
  selector:
    matchLabels:
      app: lru
  template:
    metadata:
      labels:
        app: lru
    spec:
      containers:
        -
          command:
            - redis-server
            - /conf/redis.conf
          image: "redis:7.0.4"
          name: lru
          ports:
            -
              containerPort: 6379
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
            -
              mountPath: /conf/
              name: conf
            -
              mountPath: /data/
              name: data
      volumes:
        -
          emptyDir: {}
          name: data
        -
          configMap:
            name: redis-config
          name: conf
