apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-test
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app


    spec:
      containers:
      - name: app
        image: efimius/app:v1.0.8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: app-keys
                key: app_key
          - name: APP_ID
            valueFrom:
              secretKeyRef:
                name: app-keys
                key: app_id
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-keys
                key: secret_key

            


