apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.4
        command: [ "redis-server", "/conf/redis.conf"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: conf
            mountPath: /conf/
          - name: data
            mountPath: /data/

      volumes:
        - name: data
          emptyDir: {}
        - name:  conf
          configMap:
            name: redis-config
         

            


