apiVersion: v1
kind: Service
metadata:
  labels:
    app: lru
  name: lru
  namespace: app-test
spec:
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: lru
