name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - 
      uses: actions/checkout@v3
      name: "checkout"

    - 
      name: Extract metadata for the Docker image
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/app
          ${{ secrets.DOCKER_HUB_USERNAME }}/redis


    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - 
      name: Build and push app
      uses: docker/build-push-action@v3
      with:
          context: app
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
            #          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/app:buildcache
            #          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/app:buildcache,mode=max
            #          
            #    - 
            #      name: Build and push redis
            #      uses: docker/build-push-action@v3
            #      with:
            #          context: redis
            #          push: ${{ github.event_name != 'pull_request' }}
            #          tags: ${{ steps.meta.outputs.tags }}
            #          labels: ${{ steps.meta.outputs.labels }}
            #          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/redis:buildcache
            #          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/redis:buildcache,mode=max
            #      
